$(function(){
	mui.init();
	//打开提现
	mui("body").on("tap",".putforward",function(){
		mui.openWindow({
		  url:'PutForward.html'
		});
	})
	//打开交易明细
	mui("body").on("tap",".detailInfo",function(){
		mui.openWindow({
		  url:'detailInfo.html'
		});
	})
	//二维码
	mui("body").on("tap",".code",function(){
		mui.openWindow({
		  url:'shareCode.html'
		});
	})
	//地址管理
	mui(".list").on("tap",".address",function(){
		mui.openWindow({
		  url:'address.html'
		});
	})
	//订单
	mui(".order").on("tap",".all>.r",function(){
		mui.openWindow({
		  url:'orderList.html?stat=1'
		});
	})
	mui(".order").on("tap",".stat>div",function(){
		var id=$(this).data("index")
		mui.openWindow({
		  url:'orderList.html?stat='+id
		});
	})
	//个人资料
	mui(".list").on("tap",".centerInfo",function(){
		mui.openWindow({
		  url:'centerInfo.html'
		});
	})
	//银行卡
	mui(".list").on("tap",".card",function(){
		mui.toast("正在开发中，请稍等")
	})
	//营销工具
	mui(".list").on("tap",".wd",function(){
		mui.openWindow({
		  url:'workDark.html'
		});
	})
	//我的好友
	mui(".my").on("tap",".friends",function(){
		mui.openWindow({
		  url:'friendList.html'
		});
	})
})

