$(function(){
	mui.init();
	mui("ul").on("tap",".ppt",function(){
		mui.openWindow({
			url:"ppt.html"
		})
	})
	mui("ul").on("tap",".img",function(){
		mui.openWindow({
			url:"poster.html"
		})
	})
	mui("ul").on("tap",".roll",function(){
		mui.openWindow({
			url:"roll.html"
		})
	})
})
